### ISSUE TITLE
Per-repo settings via shortest.config.ts for finding spec files

### ISSUE THREAD

**Issue by slavingia** [anti-work/shortest#33]
And more...

**Comment by poudelprakash** [comment]
This feature feels super urgent!

Most missed configuration are:
test framework of choice and preferred placement of test(whether tests go alongside components or in a separate tests/ directory)

**Comment by slavingia** [comment]
I think a simple regex for test files names should work, so one could say:

*.test.*
Or **/*_spec.rb

**Comment by slavingia** [comment]
Example generated by AI:

```
shortest:
  # Test file patterns
  test_patterns:
    - "*.test.*"
    - "**/*_spec.rb"
    - "spec/"

  # Test framework
  test_framework: "rspec"  # Options: rspec, minitest

  # Test file location
  test_location: "separate"  # Options: alongside, separate

  # Additional configuration
  ignore_patterns:
    - "node_modules/"
    - "vendor/"

  # Custom commands
  commands:
    run_tests: "bundle exec rspec"
    generate_test: "rails generate rspec:model"

  # Editor settings
  editor:
    tab_size: 2
    insert_final_newline: true
    trim_trailing_whitespace: true
```
